export type Comment = {
  id: string;
  text: string;
  author: {
    id: string;
    name: string;
    avatar?: string;
  };
  timestamp: number;
  parentId: string | null;

  reactions?: {
    upvotes: number;
    downvotes: number;
    userUpvotes: string[];
    userDownvotes: string[];
  };
  isEdited: boolean;
  editedAt?: number;
};

export type CommentThread = {
  rootComment: Comment;
  replies: Comment[];
};

// users shouldn't provide id, timestamp, or isEdited when creating a comment – those get auto-generated by commentStorage abstraction
export type createCommentInput = Omit<Comment, 'id' | 'timestamp' | 'isEdited'>;
